site_name: Sides Setup
theme:
  name: material
  logo: assets/image.png
  favicon: assets/image.png
  palette: 

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
    - Setup: getting-started/setup.md
  - Commands:
    - Setup: commands/setup.md
    - Ads: commands/ads.md
    - Design: commands/design.md
    - Utilities: commands/utilities.md
    - Prefix: commands/prefix.md
    - Autorole: commands/autorole.md
    - Suggest: commands/suggest.md
    - Moderation: commands/mod.md